language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: ZUV8jK1Wl9mceiH0iX3r0zOMW98JPkXRnbXzwPMkrwVXXlUkB+vypqsKfiHprqCsGxylB2Q0WCn6yhHzqMBRVOB72+C6PEhSqngAGUWjkzV7YKne4LJp6j9F70r67cMXzt35Lvz28UzIuwnL92m6hUA2pSSze0WaJxGqDIuWXg61kwahPbaM1iFhiwEKXOKGLV40VU4UH4U/UUf7OGQU3FzskLQfZIUnpxxCA2B6wCS0Tq0iwmCZdhZas1E0MCVCRFCuLFKnga6WXr4iioKzZVDRltIJCpwuNn/opEuBcD01conn8Dr4nownHJ19dicCnJsp0q1jY94G9v078JUNUGtVhysielLaOY02D8yK3Gw/KqgHrAQIZzvKMROhJZ460tNCwepaq8hiu4ntDXOgkICbjYF3seaBpQbaEm5JbpjMBb4OQQitZT/O09LCHRXJwhBLnB2IqRCCXX/RVyC3RIR47xvBYc+8krTCsuNZMAPuo72q1+e8vCk0lHtpjn3mfL24gBVxv9K7pcjSiYHGDxDGNblHS1L/SmwIfvwkrIDQGoBney5+2j0ySC+Ds5KPDnbiVemEMGVxbRTO7ccmabIrMdjpqOIW/PyoJ2fMf2MZzgOOce2wBiJnfsk7U9f//RQ2VLbMcM/t4jeJzXqS51UBxUJEm16n5tCdcZwS9eM=
